name: tagged
on:
  push:

env:
  is_tag: ${{ github.ref_type }} == "tag"

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: check-tag
        run: |
          echo ${{ env.is_tag }}
          echo ${{ github.ref_type }}
