name: tagged
on:
  push:

env:
  source: test

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: check-tag
        run: |
          echo ${{ env.is_tag }}
          echo ${{ github.ref_type }}
          echo ${{ github.event }}
    
